%YAML:1.0
#####################################################################
# 自瞄定补偿
#####################################################################
A03: 0
A06: 0
A10: 0
A13: 0
A16: 0
A20: 0
A23: 0
A26: 0
A30: 0
A33: 0
A36: 0
A40: 0
A43: 0
A46: 0
A50: 0

